<!doctype html><html class=no-js lang=en>
<head>
<meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<meta http-equiv=x-ua-compatible content="IE=edge">
<title>[PL] What are exceptions - blog.vallheru.pl</title>
<script>(function(a,b){a[b]=a[b].replace("no-js","js")})(document.documentElement,"className")</script>
<meta name=description content>
<meta property="og:title" content="[PL] What are exceptions">
<meta property="og:description" content="Exceptions Wstęp Co, a w zasadzie kto skłonił mnie do napisania tego artykułu? Tak naprawdę to znajomi którzy kilkukrotnie pytali o wyjątki.
Co to jest tak naprawdę ten wyjątek? Dokumentacja PHP mówi:
 An exception can be thrown, and caught (&ldquo;catched&rdquo;) within PHP. Code may be surrounded in a try block, to facilitate the catching of potential exceptions.
  pl: &ldquo;W PHP wyjątek może zostać rzucony i złapany. Kod może być objęty w blok try by ułatwić wychwytywanie potencjalnych sytuacji wyjatkowych(czyt.">
<meta property="og:type" content="article">
<meta property="og:url" content="/posts/what-are-exceptions/"><meta property="article:section" content="posts">
<meta property="article:published_time" content="2017-08-15T12:00:00+02:00">
<meta property="article:modified_time" content="2017-08-15T12:00:00+02:00">
<meta itemprop=name content="[PL] What are exceptions">
<meta itemprop=description content="Exceptions Wstęp Co, a w zasadzie kto skłonił mnie do napisania tego artykułu? Tak naprawdę to znajomi którzy kilkukrotnie pytali o wyjątki.
Co to jest tak naprawdę ten wyjątek? Dokumentacja PHP mówi:
 An exception can be thrown, and caught (&ldquo;catched&rdquo;) within PHP. Code may be surrounded in a try block, to facilitate the catching of potential exceptions.
  pl: &ldquo;W PHP wyjątek może zostać rzucony i złapany. Kod może być objęty w blok try by ułatwić wychwytywanie potencjalnych sytuacji wyjatkowych(czyt."><meta itemprop=datePublished content="2017-08-15T12:00:00+02:00">
<meta itemprop=dateModified content="2017-08-15T12:00:00+02:00">
<meta itemprop=wordCount content="1981">
<meta itemprop=keywords content>
<meta name=twitter:card content="summary">
<meta name=twitter:title content="[PL] What are exceptions">
<meta name=twitter:description content="Exceptions Wstęp Co, a w zasadzie kto skłonił mnie do napisania tego artykułu? Tak naprawdę to znajomi którzy kilkukrotnie pytali o wyjątki.
Co to jest tak naprawdę ten wyjątek? Dokumentacja PHP mówi:
 An exception can be thrown, and caught (&ldquo;catched&rdquo;) within PHP. Code may be surrounded in a try block, to facilitate the catching of potential exceptions.
  pl: &ldquo;W PHP wyjątek może zostać rzucony i złapany. Kod może być objęty w blok try by ułatwić wychwytywanie potencjalnych sytuacji wyjatkowych(czyt.">
<link rel=preconnect href=https://fonts.gstatic.com crossorigin>
<link rel=dns-prefetch href=//fonts.googleapis.com>
<link rel=dns-prefetch href=//fonts.gstatic.com>
<link rel=stylesheet href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">
<link rel=stylesheet href=/css/style.css>
<link rel=stylesheet href=/css/custom.css>
<link rel="shortcut icon" href=/favicon.ico>
</head>
<body class=body>
<div class="container container--outer">
<header class=header>
<div class="container header__container">
<div class="logo logo--mixed">
<a class=logo__link href=/ title=blog.vallheru.pl rel=home>
<div class="logo__item logo__imagebox">
<img class=logo__img src=/img/placeholder.png>
</div><div class="logo__item logo__text">
<div class=logo__title>blog.vallheru.pl</div>
<div class=logo__tagline>Personal blog</div>
</div>
</a>
</div>
<div class=divider></div>
</div>
</header>
<div class="wrapper flex">
<div class=primary>
<main class=main role=main>
<article class=post>
<header class=post__header>
<h1 class=post__title>[PL] What are exceptions</h1>
<div class="post__meta meta"><div class="meta__item-author meta__item">
<svg class="meta__icon icon icon-author" width="16" height="16" viewBox="0 0 12 16"><path d="M6 1c2.2.0 3.5 2 3.5 4.5C9.5 7 8.9 8.2 8 9c2.9.8 4 2.5 4 5v1H0v-1c0-2.5 1.1-4.2 4-5-.9-.8-1.5-2-1.5-3.5C2.5 3 3.8 1 6 1z"/></svg><span class=meta__text>daniel1302</span>
</div>
<div class="meta__item-datetime meta__item">
<svg class="meta__icon icon icon-time" width="16" height="14" viewBox="0 0 30 28"><path d="M15 0C7 0 1 6 1 14s6 14 14 14 14-6 14-14S23 0 15 0zm0 25C9 25 4 20 4 14S9 3 15 3s11 5 11 11-5 11-11 11zm1-18h-2v8.4l6.8 4.4L22 18l-6-3.8V7z"/></svg><time class=meta__text datetime=2017-08-15T12:00:00+02:00>2017-08-15</time></div></div>
</header>
<div class="post__toc toc">
<div class=toc__title>Page content</div>
<div class=toc__menu>
<nav id=TableOfContents>
<ul>
<li>
<ul>
<li><a href=#wstęp>Wstęp</a></li>
<li><a href=#co-to-jest-tak-naprawdę-ten-wyjątek>Co to jest tak naprawdę ten wyjątek?</a></li>
<li><a href=#po-co-nam-to-jak-to-działa-co-to-jest-to-rzucanie-i-łapanie>Po co nam to? Jak to działa? Co to jest to &ldquo;rzucanie&rdquo; i &ldquo;łapanie&rdquo;</a></li>
</ul>
</li>
</ul>
</nav>
</div>
</div><div class="content post__content clearfix">
<h1 id=exceptions>Exceptions</h1>
<h3 id=wstęp>Wstęp</h3>
<p>Co, a w zasadzie kto skłonił mnie do napisania tego artykułu? Tak naprawdę to znajomi którzy kilkukrotnie pytali o wyjątki.</p>
<h3 id=co-to-jest-tak-naprawdę-ten-wyjątek>Co to jest tak naprawdę ten wyjątek?</h3>
<p>Dokumentacja PHP mówi:</p>
<blockquote>
<p>An exception can be thrown, and caught (&ldquo;catched&rdquo;) within PHP. Code may be surrounded in a try block, to facilitate the catching of potential exceptions.</p>
</blockquote>
<blockquote>
<p>pl: &ldquo;W PHP wyjątek może zostać rzucony i złapany. Kod może być objęty w blok try by ułatwić wychwytywanie potencjalnych sytuacji wyjatkowych(czyt. &ldquo;niechcianych).</p>
</blockquote>
<p>No spoko, ale czym ten wyjątek jest? Chyba nigdzie nie znalazłem odpowiedzi na to pytanie&mldr;
Wyjątek to nic innego jak zwykła klasa wbudowana w język programowania, która posiada w sobie jakieś predefiniowane metody oraz własności(zmienne). Klasy wyjątków przeważnie mogą zostać rozbudowane (o ile nie są finalne). Rozszeżać taką klasę można jak każdą inną poprzez dziedziczenie. Jak mówi dokumentacja klasy &ldquo;wyjątków&rdquo; mogą być &ldquo;rzucane&rdquo; i &ldquo;łapane&rdquo; jest to specjalna funkcjonalność klas z rodziny Exception.</p>
<h3 id=po-co-nam-to-jak-to-działa-co-to-jest-to-rzucanie-i-łapanie>Po co nam to? Jak to działa? Co to jest to &ldquo;rzucanie&rdquo; i &ldquo;łapanie&rdquo;</h3>
<p>Nie bez powodu czynności które możemy wykonywać z wyjątkami nazwyają się &ldquo;rzucaniem&rdquo; i &ldquo;łapaniem&rdquo;. Tak jak w normalnym świecie gdy rzucimy na przykład piłkę możemy ją złapać aby rzucić ją kolejny raz albo poprostu odłożyć na swoje miejsce. W językach programowania zachodzi pewna analogia, którą postaram się niżej wyjaśnić.</p>
<h6 id=po-co-są-wyjątki>Po co są wyjątki?</h6>
<p>Tak naprawdę jest to jedno z pytań na które niema jednoznacznej odpowiedzi, ale ogólnie pomagają nam one sterować aplikacją, wyłapywać błędy, które wcześniej przewidzieliśmy, że mogą wystąpić.
Prosty przykład:</p>
<blockquote>
<p><strong>Zadanie:</strong> Napisz program który będzie analizował dokumenty XML, szukał w nich wszystkich numerów telefonu i zwracał nam je.</p>
</blockquote>
<p>Mamy zadanie, więc napiszmy sobie algorytm:</p>
<pre><code>1. Otwórz plik XML.
2. Otwórz główny węzeł i zacznij przetwarzać po kolei wszystkie węzły znajdujące się w nim.
3. Dla każdego węzła spradź czy zawiera numer telefonu
    - Jeśli tak to zapisz do tablicy.
    - Jeśli nie to pomiń aktualny węzeł
4. Zwróć tablicę z znalezionymi numerami.
</code></pre><p>Oczywiście jest to bardzo uproszczony algorytm, ale i tutaj mogą pojawić się sytuacje których nie chcemy. Przeanalizujmy sobie punkt po punkcie nasz algorytm:</p>
<ol>
<li>
<p>Otwórz plik XML.</p>
<ul>
<li>Tutaj mogą pojawić się problemy w postaci: <strong>nieistniejącego pliku</strong> oraz tego, że wczytany plik <strong>nie jest poprawny plikiem XML</strong>. Jakie naspstwa mają takie błędy?
<ul>
<li>Jeśli spróbujemy odczytać plik który nie istnieje to nie zostanie utworzony obiekt &ldquo;uchwytu pliku&rdquo; i będzie on NULL&rsquo;em co spowoduje błędy w dalszym działaniu programu.</li>
<li>Jeśli plik nie jest plikiem XML to nie utworzymy obiektu Parsera przez co też będziemy operowali na pustym wskaźniku.</li>
</ul>
</li>
</ul>
</li>
<li>
<p>Otwórz główny węzeł i zacznij przetwarzać po kolei wszystkie węzły znajdujące się w nim.</p>
</li>
</ol>
<ul>
<li>Ale co gdy dokument jest pusty i <strong>główny węzeł nie istnieje</strong>? Gdy nie wczytamy węzła i zaczniemy sprawdzać czy ma on dzieci? Znów będziemy chcieli operować na pustym wskaźniku.</li>
</ul>
<p>I moglibyśmy wyliczać kolejne błędy, ale nie to jest celem tego artykułu. Jak widzimy dając użytkownikowi program musimy przewidzieć masę niestandardowych rzeczy, do których może doprowadzić użytkownik korzystając z naszego programu. Właśnie w obsłudze takich rzeczy pomagają nam wyjątki.</p>
<h5 id=jak-działają-wyjątki>Jak działają wyjątki?</h5>
<p>Po pierwsze wyjątek musi zostać rzucony poprzez słowo kluczowe throw</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#34;...&#34;</span>); 
</code></pre></div><p>w tym momencie interpreter <strong>przerywa</strong> swoje działanie i wykonuje <strong>skok</strong> w inne miejsce. Jeśli wyjątek został rzucony poza blokiem &ldquo;<strong>try</strong>&rdquo; to program kończy się <strong>błędem</strong>. Natomiast jeśli rzuciliśmy wyjątek w kodzie który jest objęty klamrami bloku <strong>try</strong> { }, to program wykonuje skok do najbliższego bloku <strong>catch</strong> który <strong>jest go w stanie złapać</strong>. W momęcie złapania wyjątku <strong>odzyskujemy kontrolę</strong> nad programem i dostajemy dostęp do rzuconego wyjątku. Taki rzucony wyjątek może mieć w sobie informację o błędzie który wystąpił w programie. Najprostszymi informacjami niesionymi przez taki obiekt są: wiadomośc, kod błędu, plik w którym został wyrzucony, linię itp. Oczywiście sami możemy definiować jakie informacje ma taki obiekt.</p>
<blockquote>
<blockquote>
<p>Analizując poniższy przykład zastanów się które działania się wykonają po kolei i jaka jest wartość zmiennej $i po wykonaniu programu.
Przykład:</p>
</blockquote>
</blockquote>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>try</span> {
                <span style=color:#66d9ef>try</span> {
                    <span style=color:#75715e>//Dzialanie 1:
</span><span style=color:#75715e></span>                    $i <span style=color:#f92672>=</span> <span style=color:#ae81ff>0</span>;
                    <span style=color:#75715e>//Dzialanie 2:
</span><span style=color:#75715e></span>                    $i <span style=color:#f92672>=</span> $i <span style=color:#f92672>+</span> <span style=color:#ae81ff>10</span>; <span style=color:#75715e>//Do tego momentu kod się wykonuje normalnie
</span><span style=color:#75715e></span>
                    <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>RuntimeException</span>(<span style=color:#e6db74>&#34;Komunikat&#34;</span>); <span style=color:#75715e>//Tutaj po rzuceniu wyjątku następuje skok do najbliższego bloku catch który jest w stanie złapać ten wyjątek
</span><span style=color:#75715e></span>
                    <span style=color:#75715e>//Dzialanie 3:
</span><span style=color:#75715e></span>                    $i <span style=color:#f92672>=</span> $i <span style=color:#f92672>+</span> <span style=color:#ae81ff>5</span>; <span style=color:#75715e>//Ten kod się nigdy nie wykona, ponieważ został przeskoczony przez wyrzucenie wyjątku
</span><span style=color:#75715e></span>                } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>LogicException</span> $ex) {
                    <span style=color:#66d9ef>print</span>(<span style=color:#e6db74>&#39;Wystąpił wyjątek aplikacji: &#39;</span><span style=color:#f92672>.</span>$ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getMessage</span>()); <span style=color:#75715e>//Ten komunikat nie zostaje wyświetlony ponieważ my rzuciliśmy RuntimeException a ten blok obsługuje wyjątek logiczny
</span><span style=color:#75715e></span>                }
                
                <span style=color:#75715e>//Dzialanie 4:
</span><span style=color:#75715e></span>                $i <span style=color:#f92672>=</span> $i <span style=color:#f92672>+</span> <span style=color:#ae81ff>2</span>; <span style=color:#75715e>//Ten kod też nie zostanie wykonany bo wyjątek nie został złapany więc próbuje skakać dalej do kolejnego bloku catch
</span><span style=color:#75715e></span>            } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>RuntimeException</span> $ex) { <span style=color:#75715e>//W tym miejscu nasz wyjątek który rzuciliśmy zostaje złapany i wykona się kod z tego bloku
</span><span style=color:#75715e></span>                <span style=color:#75715e>//W tym momencie odzyskujemy pełną kontrolę nad działaniem programu
</span><span style=color:#75715e></span>                <span style=color:#66d9ef>print</span>(<span style=color:#e6db74>&#39;Wystąpił wyjątek aplikacji typu Runtime: &#39;</span><span style=color:#f92672>.</span>$ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getMessage</span>()); <span style=color:#75715e>//Na ekranie zobaczymy ten komunikat
</span><span style=color:#75715e></span>            }

            <span style=color:#75715e>//Dzialanie 5:
</span><span style=color:#75715e></span>            $i <span style=color:#f92672>=</span> $i <span style=color:#f92672>+</span> <span style=color:#ae81ff>20</span>; <span style=color:#75715e>//Ten kod się wykona się już normalnie
</span></code></pre></div><p>Wykonają się działania: 1, 2, 5, więc zmienna $i = $i + 10 + 20. Wiec po wykonaniu programu $i = 30</p>
<p>Przykład:</p>
<blockquote>
<p><strong>Zadanie:</strong> Napisz program który umożliwi dzielenie dwóch liczb.</p>
</blockquote>
<p>Zadanie bardzo proste ale wystarczy do zobrazowania zasady działania wyjątków</p>
<p>Sama funkcjonalność prezentuje się następująco</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>Calculator</span>
{
	<span style=color:#66d9ef>public</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>float</span> $a, <span style=color:#a6e22e>float</span> $b)<span style=color:#f92672>:</span> <span style=color:#a6e22e>float</span>
    {
        <span style=color:#66d9ef>return</span> $a <span style=color:#f92672>/</span> $b;
    }
}
</code></pre></div><p>Kod jest raczej prosty, zawiera jedną metodę która wykonuje dzielenie, ale rozważmy co się stanie jeśli wykonamy taki kod:</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php>$calc <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Calculator</span>();
$result <span style=color:#f92672>=</span>  $calc<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>div</span>(<span style=color:#ae81ff>10</span>, <span style=color:#ae81ff>0</span>);
<span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Wynik dzielenia 10 / 0 to: &#39;</span><span style=color:#f92672>.</span>$result;
</code></pre></div><p>Otrzymamy błąd który nie wygląda przyjemnie, dodatkowo powyższe działanie powoduje niepoprawne działanie naszej aplikacji.</p>
<pre><code>Warning: Division by zero in calculator.php on line 7 
Wynik dzielenia 10 / 0 to:
</code></pre><p>A co jeśli podamy argument większy niż możemy?</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php>$calc <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Calculator</span>();
$result <span style=color:#f92672>=</span>  $calc<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>, <span style=color:#ae81ff>2</span>);
<span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Wynik dzielenia &#39;</span><span style=color:#f92672>.</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>)<span style=color:#f92672>.</span><span style=color:#e6db74>&#39; / 0 to: &#39;</span><span style=color:#f92672>.</span>$result;
</code></pre></div><p>W takim wypadku otrzymamy mega niedokładny wynik, wynika to z tego, że język PHP, gdy przepełnimy wartość zmiennej INT, przekształca ją do zmiennej typu float, zapisanej w postaci wykładniczej.
Oto co otrzymamy na ekranie:</p>
<pre><code>Wynik dzielenia 8.5070591730235E+37 / 0 to: 4.2535295865117E+37
</code></pre><p>Oczywiście wynik jest bardzo niedokładny, nie chcemy aby potem użytkownicy naszego kalkulatora się skarżyli, więc zablokujemy tą funkcjonalnośc, opcjonalnie w przyszłości możemy dodać w to miejsce jakiś algorytm pozwalający na dzialania na tak ogromnych liczbach.</p>
<p>I tutaj możemy to rozwiązać na dwa sposoby mniej elegancki manualny, ale z pomocą przychodza nam wyjątki.
Pierwszy sposób:</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>Calculator</span>
{
    <span style=color:#66d9ef>public</span> $error;


    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>float</span> $a, <span style=color:#a6e22e>float</span> $b)<span style=color:#f92672>:</span> <span style=color:#f92672>?</span><span style=color:#a6e22e>float</span>
    {
        <span style=color:#66d9ef>if</span> ($a <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span> <span style=color:#f92672>||</span> $b <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span>) {
            $this<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>error</span> <span style=color:#f92672>=</span> <span style=color:#e6db74>&#39;Wpisane wartości są zbyt duże&#39;</span>;
            <span style=color:#66d9ef>return</span> <span style=color:#66d9ef>null</span>;
        }

        <span style=color:#66d9ef>if</span> ($b <span style=color:#f92672>===</span> <span style=color:#ae81ff>0.0</span>) {
            $this<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>error</span> <span style=color:#f92672>=</span> <span style=color:#e6db74>&#39;Dzielenie przez 0 jest zabronione&#39;</span>;
            <span style=color:#66d9ef>return</span> <span style=color:#66d9ef>null</span>;
        }

        <span style=color:#66d9ef>return</span> $a <span style=color:#f92672>/</span> $b;
    }
}



$calc <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Calculator</span>();
$result <span style=color:#f92672>=</span>  $calc<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>, <span style=color:#ae81ff>2</span>);

<span style=color:#66d9ef>if</span> ($result <span style=color:#f92672>!==</span> <span style=color:#66d9ef>null</span>) {
    <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Wynik dzielenia &#39;</span><span style=color:#f92672>.</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>)<span style=color:#f92672>.</span><span style=color:#e6db74>&#39; / 0 to: &#39;</span><span style=color:#f92672>.</span>$result;    
} <span style=color:#66d9ef>else</span> {
    <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Podczas działania kalkulatora wystąpił błąd: &#39;</span><span style=color:#f92672>.</span>$calc<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>error</span>;
}
</code></pre></div><p>Dokonaliśmy kilku modyfikacji kodu. Po pierwsze teraz w klasie kalkulatora przchowujemy błąd oraz podczas wystąpienia błędu zwracany jest null.
Aby funkcja pozwoliła nam zwrócić wartośc null musimy dodać znak zapytania przed zwracanym typem.</p>
<p>Jednak nie mamy informacji w której lini wystąpił błąd, w przypadku gdybyśmy chcieli zalogować błąd do logów.</p>
<p>Aby zapewnić taką funkcjonalność możem skorzystać z wyjątków, zatem napiszmy prosty program:</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>Calculator</span>
{
    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>float</span> $a, <span style=color:#a6e22e>float</span> $b)<span style=color:#f92672>:</span> <span style=color:#a6e22e>float</span>
    {
        <span style=color:#66d9ef>if</span> ($a <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span> <span style=color:#f92672>||</span> $b <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span>) {
            <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#39;Wpisane wartości są zbyt duże&#39;</span>, <span style=color:#ae81ff>10</span>);
        }

        <span style=color:#66d9ef>if</span> ($b <span style=color:#f92672>===</span> <span style=color:#ae81ff>0.0</span>) {
            <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#39;Dzielenie przez 0 jest zabronione&#39;</span>, <span style=color:#ae81ff>11</span>);
        }

        <span style=color:#66d9ef>return</span> $a <span style=color:#f92672>/</span> $b;
    }
}



$calc <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Calculator</span>();
<span style=color:#66d9ef>try</span> {
    $result <span style=color:#f92672>=</span>  $calc<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>, <span style=color:#ae81ff>2</span>);
    <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Wynik dzielenia &#39;</span><span style=color:#f92672>.</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>)<span style=color:#f92672>.</span><span style=color:#e6db74>&#39; / 0 to: &#39;</span><span style=color:#f92672>.</span>$result; 
} <span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>Exception</span> $ex) {
    <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Podczas działania kalkulatora wystąpił błąd: &#39;</span><span style=color:#f92672>.</span>$ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getMessage</span>();
    <span style=color:#66d9ef>echo</span> <span style=color:#a6e22e>PHP_EOL</span>;
    <span style=color:#66d9ef>echo</span> <span style=color:#a6e22e>sprintf</span>(
        <span style=color:#e6db74>&#39;Błąd wystąpił w pliku: %s, w lini %d, kod błędu: %d&#39;</span>,
        $ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getFile</span>(),
        $ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getLine</span>(),
        $ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getCode</span>()
    );
}
</code></pre></div><p>Oto wynik działania:</p>
<pre><code>Podczas działania kalkulatora wystąpił błąd: Wpisane wartości są zbyt duże 
Błąd wystąpił w pliku: calculator, w lini 6, kod błędu: 10
</code></pre><p>Co zyskujemy korzystając z wyjątków poza tymi dodatkowymi informacjami?
Pozbywamy się if&rsquo;ów, kod staje się prostszy, pozwala dokładnie sterowac przepływem informacji w naszym programie.</p>
<p>W naszym przykładzie skorzystaliśmy z wbudowanej w język klasy Exception, co nie jest najlepszym przykładem.
Rozbudujmy nasz program o jakąś klasę wyświetlającą wynik na ekranie.</p>
<p>Oto nasz trochę bardziej rozbudowany kod:</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#f92672>&lt;?</span><span style=color:#a6e22e>php</span>
<span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>RendererException</span> <span style=color:#66d9ef>extends</span> <span style=color:#a6e22e>Exception</span>
{
    <span style=color:#66d9ef>const</span> <span style=color:#66d9ef>UNDEFINED_WINDOW_CODE</span> <span style=color:#f92672>=</span> <span style=color:#ae81ff>21</span>;
    
    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>static</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>forUndefinedWindow</span>(<span style=color:#a6e22e>Throwable</span> $prev <span style=color:#f92672>=</span> <span style=color:#66d9ef>null</span>) 
    {
        <span style=color:#66d9ef>return</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>self</span>(<span style=color:#e6db74>&#39;Nie można wyrenderować. Obiekt okna jest pusty&#39;</span>, <span style=color:#a6e22e>self</span><span style=color:#f92672>::</span><span style=color:#a6e22e>UNDEFINED_WINDOW_CODE</span>, $prev);
    }    
}

<span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>CalculatorException</span> <span style=color:#66d9ef>extends</span> <span style=color:#a6e22e>Exception</span>
{
    <span style=color:#66d9ef>const</span> <span style=color:#66d9ef>UNDEFINED_WINDOW_CODE</span> <span style=color:#f92672>=</span> <span style=color:#ae81ff>0</span>;
    
    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>static</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>forDivisionByZero</span>(<span style=color:#a6e22e>Throwable</span> $prev <span style=color:#f92672>=</span> <span style=color:#66d9ef>null</span>) 
    {
        <span style=color:#66d9ef>return</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>self</span>(<span style=color:#e6db74>&#39;Dzielenie przez 0 jest zabronione&#39;</span>, <span style=color:#a6e22e>self</span><span style=color:#f92672>::</span><span style=color:#a6e22e>UNDEFINED_WINDOW_CODE</span>, $prev);
    }
    
    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>static</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>forArgumentOverflow</span>(<span style=color:#a6e22e>Throwable</span> $prev <span style=color:#f92672>=</span> <span style=color:#66d9ef>null</span>) 
    {
        <span style=color:#66d9ef>return</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>self</span>(<span style=color:#e6db74>&#39;Wpisane wartości są zbyt duże&#39;</span>, <span style=color:#a6e22e>self</span><span style=color:#f92672>::</span><span style=color:#a6e22e>UNDEFINED_WINDOW_CODE</span>, $prev);
    } 
}



<span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>Renderer</span>
{
    <span style=color:#66d9ef>private</span> $window;
    
    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>renderNotification</span>() {
        <span style=color:#75715e>//....
</span><span style=color:#75715e></span>        <span style=color:#66d9ef>if</span> ($this<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>window</span> <span style=color:#f92672>===</span> <span style=color:#66d9ef>null</span>) {
            <span style=color:#66d9ef>throw</span> <span style=color:#a6e22e>RendererException</span><span style=color:#f92672>::</span><span style=color:#a6e22e>forUndefinedWindow</span>();
        }
        
        <span style=color:#75715e>//.... Wyświetlanie na ekranie
</span><span style=color:#75715e></span>    }
}


<span style=color:#66d9ef>Class</span> <span style=color:#a6e22e>Calculator</span>
{
    <span style=color:#66d9ef>public</span> <span style=color:#66d9ef>function</span> <span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>float</span> $a, <span style=color:#a6e22e>float</span> $b)<span style=color:#f92672>:</span> <span style=color:#a6e22e>float</span>
    {
        <span style=color:#66d9ef>if</span> ($a <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span> <span style=color:#f92672>||</span> $b <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span>) {
            <span style=color:#66d9ef>throw</span> <span style=color:#a6e22e>CalculatorException</span><span style=color:#f92672>::</span><span style=color:#a6e22e>forArgumentOverflow</span>();
        }

        <span style=color:#66d9ef>if</span> ($b <span style=color:#f92672>===</span> <span style=color:#ae81ff>0.0</span>) {
            <span style=color:#66d9ef>throw</span> <span style=color:#a6e22e>CalculatorException</span><span style=color:#f92672>::</span><span style=color:#a6e22e>forDivisionByZero</span>();
        }

        <span style=color:#66d9ef>return</span> $a <span style=color:#f92672>/</span> $b;
    }
}



$calc <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Calculator</span>();
<span style=color:#66d9ef>try</span> {
    $renrerer <span style=color:#f92672>=</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Renderer</span>();
    
    
    $result <span style=color:#f92672>=</span>  $calc<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>div</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>, <span style=color:#ae81ff>2</span>);
    $renderer<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>renderNotification</span>(<span style=color:#e6db74>&#39;Wynik dzielenia &#39;</span><span style=color:#f92672>.</span>(<span style=color:#a6e22e>PHP_INT_MAX</span><span style=color:#f92672>*</span><span style=color:#a6e22e>PHP_INT_MAX</span>)<span style=color:#f92672>.</span><span style=color:#e6db74>&#39; / 0 to: &#39;</span><span style=color:#f92672>.</span>$result); 
} <span style=color:#66d9ef>catch</span>(<span style=color:#a6e22e>CalculatorException</span> $ex) {
    <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Podczas działania kalkulatora wystąpił błąd: &#39;</span><span style=color:#f92672>.</span>$ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getMessage</span>();
    <span style=color:#66d9ef>echo</span> <span style=color:#a6e22e>PHP_EOL</span>;
    <span style=color:#66d9ef>echo</span> <span style=color:#a6e22e>sprintf</span>(
        <span style=color:#e6db74>&#39;Błąd wystąpił w pliku: %s, w lini %d, kod błędu: %d&#39;</span>,
        $ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getFile</span>(),
        $ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getLine</span>(),
        $ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getCode</span>()
    );
} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>RendererException</span> $ex) {
    <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Podczas renderowania obrazu wystąpił błąd: &#39;</span><span style=color:#f92672>.</span>$ex<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getMessage</span>();
}
</code></pre></div><p>Dodaliśmy tutaj 3 nowe klasy:
- <strong>Renderer</strong> - klasa która odpowiada za wyświetlanie okienek, nie musimy wiedzieć jak działa, ważne, że rzuca wyjątek gdy stanie się coś niewłaściwego.
- <strong>RendererException</strong> - klasa która dziedziczy po Exception i można nią rzucać. Klasa będzie rzucana gdy wystąpi błąd podczas renderowania okienek naszej aplikacji.
- <strong>CalculatorException</strong> - klasa która będzie rzucana podczas wystąpienia błędu w czasie obliczania.</p>
<p>Można tutaj zauważyć znaczącą różnice, dlaczego nie rzucać wyjątków klasy Exception, po co tworzyć nowe klasy?
Jest to trafne pytanie. Otóż lepiej stworzyć osobne klasy bo poprawia nam to organizację kodu w naszej aplikacji. Pozwala lepiej zorganizować przepływ informacji i ułatwić modfikację kodu. Dodatkowo jedne wyjątki możemy łapać w jednym miejscu drugie w drugim&mldr;</p>
<p>Drugą ważną rzeczą, jest to, że klasy wyjątków posiadają same metody statyczne. Robimy to po to, aby rodzielić implementację od obsługi błędów, dodatkowo poprawia nam to czytelność, bo co jeśli nasz kod będzie czytał np. programista z francji to który fragment będzie dla niego bardziej zrozumiały:</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>if</span> ($a <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span> <span style=color:#f92672>||</span> $b <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span>) {
    <span style=color:#66d9ef>throw</span> <span style=color:#a6e22e>CalculatorException</span><span style=color:#f92672>::</span><span style=color:#a6e22e>forArgumentOverflow</span>();
}
</code></pre></div><p>czy może:</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#66d9ef>if</span> ($a <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span> <span style=color:#f92672>||</span> $b <span style=color:#f92672>&gt;</span> <span style=color:#a6e22e>PHP_INT_MAX</span>) {
    <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#39;Wpisane wartości są zbyt duże&#39;</span>, <span style=color:#ae81ff>10</span>);
}
</code></pre></div><p>Oczywiście, że ten pierwszy. W tym trywialnym przykładzie mozna oczywiści odczytać z warunków dlaczego wyjątek jest rzucany, ale nie zawsze tak będzie. Poza tym izoluje nam to ładnie moduły. Dodatkowo wszystkei komunikaty mamy w jednym miejscu, oraz widzimy w jakich wypadkach jest rzucany konkretny wyjątek.</p>
<p>Ostatnią ważną rzeczą jest to, ze wyjątki można rzucać w łańcuchu, mamy tym samym możliwość śledzenai jak po kolei występowały błędy w naszej aplikacji.</p>
<div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-php data-lang=php><span style=color:#f92672>&lt;?</span><span style=color:#a6e22e>php</span>
<span style=color:#66d9ef>try</span> {
    <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#39;Msg1&#39;</span>, <span style=color:#ae81ff>10</span>); <span style=color:#75715e>//1
</span><span style=color:#75715e></span>} <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>Exception</span> $ex) {
    <span style=color:#66d9ef>try</span> {
        <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#39;Msg2&#39;</span>, <span style=color:#ae81ff>10</span>, $ex); <span style=color:#75715e>//2
</span><span style=color:#75715e></span>    } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>Exception</span> $ex1) {
        <span style=color:#66d9ef>try</span> {
            <span style=color:#66d9ef>throw</span> <span style=color:#66d9ef>new</span> <span style=color:#a6e22e>Exception</span>(<span style=color:#e6db74>&#39;Msg3&#39;</span>, <span style=color:#ae81ff>10</span>, $ex1); <span style=color:#75715e>//3
</span><span style=color:#75715e></span>        } <span style=color:#66d9ef>catch</span> (<span style=color:#a6e22e>Exception</span> $ex2) {
            
            $tmpEx <span style=color:#f92672>=</span> $ex2; <span style=color:#75715e>//4
</span><span style=color:#75715e></span>            <span style=color:#66d9ef>do</span> {
                <span style=color:#66d9ef>echo</span> <span style=color:#e6db74>&#39;Wyjątek: &#39;</span><span style=color:#f92672>.</span>$tmpEx<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getMessage</span>()<span style=color:#f92672>.</span><span style=color:#a6e22e>PHP_EOL</span>;
                $tmpEx <span style=color:#f92672>=</span> $tmpEx<span style=color:#f92672>-&gt;</span><span style=color:#a6e22e>getPrevious</span>();
                
            } <span style=color:#66d9ef>while</span>($tmpEx <span style=color:#f92672>!==</span> <span style=color:#66d9ef>null</span>);
        }
    }
}
</code></pre></div><p>Wyjaśnijmy ten kod:
Po koleji są rzucane 3 wyjątki w kolejności 1, 2, 3. Dodatkowo podczas rzucania wyjątku 2 i 3 przekazywane są poprzednie wyjątki. W miejscu oznaczonym 4 jest prosta pętla do wyświetlania wszystkich rzuconych wyjątków. Wyjątki oczywiście wyświetlimy w kolejności odwrotnej.</p>
<p>Oto wynik programu:</p>
<pre><code>Wyjątek: Msg3 
Wyjątek: Msg2 
Wyjątek: Msg1
</code></pre><p>Konstrukcja często jest stosowana aby określić skąd się wziął konkretny błąd, co go spowodowało.</p>
<p>Dodatkowym źródłem informacji jest dokumentacja PHP:
<a href=http://php.net/manual/en/language.exceptions.php>Exceptions</a>
<a href=http://php.net/manual/en/language.exceptions.extending.php>Extending Exceptions</a>
<a href=http://php.net/manual/en/language.errors.php7.php>Errors</a></p>
</div>
</article>
</main>
<div class="authorbox clearfix">
<figure class=authorbox__avatar>
<img alt="daniel1302 avatar" src=/img/avatar.png class=avatar height=90 width=90>
</figure>
<div class=authorbox__header>
<span class=authorbox__name>About daniel1302</span>
</div>
<div class=authorbox__description>
Devops with AWS and golang
</div>
</div>
<nav class="pager flex">
<div class="pager__item pager__item--prev">
<a class=pager__link href=/posts/php-and-nginx-monitoring/ rel=prev>
<span class=pager__subtitle>«&#8201;Previous</span>
<p class=pager__title>[PL] Monitoring PHP + NGINX</p>
</a>
</div>
<div class="pager__item pager__item--next">
<a class=pager__link href=/posts/setup-kvm-on-a-physical-server/ rel=next>
<span class=pager__subtitle>Next&#8201;»</span>
<p class=pager__title>Setup KVM on a physical server</p>
</a>
</div>
</nav>
<section class=comments>
<div id=disqus_thread></div>
<script type=application/javascript>var disqus_config=function(){};(function(){if(["localhost","127.0.0.1"].indexOf(window.location.hostname)!=-1){document.getElementById('disqus_thread').innerHTML='Disqus comments not available by default when the website is previewed locally.';return}var b=document,a=b.createElement('script');a.async=!0,a.src='//Disqus.disqus.com/embed.js',a.setAttribute('data-timestamp',+new Date),(b.head||b.body).appendChild(a)})()</script>
<noscript>Please enable JavaScript to view the <a href=https://disqus.com/?ref_noscript>comments powered by Disqus.</a></noscript>
<a href=https://disqus.com class=dsq-brlink>comments powered by <span class=logo-disqus>Disqus</span></a>
</section>
</div>
</div>
<footer class=footer>
<div class="container footer__container flex">
<div class=footer__copyright>
&copy; 2021 John Doe.
<span class=footer__copyright-credits>Generated with <a href=https://gohugo.io/ rel="nofollow noopener" target=_blank>Hugo</a> and <a href=https://github.com/Vimux/Mainroad/ rel="nofollow noopener" target=_blank>Mainroad</a> theme.</span>
</div>
</div>
</footer>
</div>
<script async defer src=/js/menu.js></script>
<script src=/js/custom.js></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML" async></script>
</body>
</html>